### ISSUE TITLE
新增API接口地址复制功能

### ISSUE THREAD

**Issue by jasonpyf** [xiaoymin/knife4j#238]
![1592475931(1)](https://user-images.githubusercontent.com/16953632/85010406-84d34000-b192-11ea-9cd0-46b69a8aaf6d.png)
前端的小伙伴复制接口很不容易，希望添加一个复制接口的按钮

**Comment by xiaoymin** [comment]
用2.0.4  已经加上

**Comment by lin-zhenhua** [comment]
前端的小伙伴复制接口的时候说不要项目前缀，希望复制接口按钮可以自定义过滤路径
![image](https://user-images.githubusercontent.com/58074265/140602627-c0c0ce10-0d06-412d-814b-930ab28fec7a.png)

**Comment by xiaoymin** [comment]
一个复制 还需要自定义过滤啊？未免太多余了吧

**Comment by lin-zhenhua** [comment]
没办法，前端小伙伴说每次都要手动删除项目前缀，索性都不点复制接口按钮了，鼠标划拉复制



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年11月8日(星期一) 下午3:41
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [xiaoymin/swagger-bootstrap-ui] 新增API接口地址复制功能 (#238)





 
一个复制 还需要自定义过滤啊？未免太多余了吧
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
