### ISSUE TITLE
繁體中文支援嗎

### ISSUE THREAD

**Issue by faithfay** [xiaoymin/knife4j#382]
未來可否增加繁體中文?

**Comment by xiaoymin** [comment]
没有这个计划



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年9月1日(星期三) 上午10:17
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [xiaoymin/swagger-bootstrap-ui] 繁體中文支援嗎 (#382)





 
未來可否增加繁體中文?
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
