### ISSUE TITLE
doc.html响应示例数据格式混乱

### ISSUE THREAD

**Issue by zhk19515** [xiaoymin/knife4j#744]
1.预览json数据出现格式混乱。
2.浏览器控制台提示一下错误：
Refused to apply inline style because it violates the following Content Security Policy directive: "default-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-RP8P1W7X4jJHFckJSyTe73IGxaZoW+sfHZ19U3bRh80='), or a nonce ('nonce-...') is required to enable inline execution. Note that hashes do not apply to event handlers, style attributes and javascript: navigations unless the 'unsafe-hashes' keyword is present. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.

Refused to load the image 'data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==' because it violates the following Content Security Policy directive: "default-src 'self'". Note that 'img-src' was not explicitly set, so 'default-src' is used as a fallback.

**Comment by zhk19515** [comment]
![Xnip2024-02-28_16-01-08](https://github.com/xiaoymin/knife4j/assets/37992546/d65bbc71-e893-428c-a285-26d80d2123ba)

**Comment by xiaoymin** [comment]
给出版本和代码示例 ，帮助作者复现

**Comment by zhk19515** [comment]
knife4j-spring-boot-starter 
version:2.0.4

**Comment by xiaoymin** [comment]
没代码我怎么看？ 或者你可以升级一下版本

**Comment by 805728578** [comment]
@zhk19515 你可以升级到v2.0.9或4.5.0，目前这两个版本比较稳定，而且目前我们开发生产环境均未出现乱码情况

**Comment by glm1024** [comment]
我出现同样的问题了

pom依赖：

<dependency>
	<groupId>com.github.xiaoymin</groupId>
	<artifactId>knife4j-openapi2-spring-boot-starter</artifactId>
	<version>4.5.0</version>
</dependency>

操作系统：mac os

浏览器：edge、safari

f12查看控制台报错信息：

chunk-vendors.d51cf6f8.js:2  Refused to apply inline style because it violates the following Content Security Policy directive: "default-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-FZKmwBmGiuBzy0U/fIz58mtwbVOCY+xktuNV/sAz2wM='), or a nonce ('nonce-...') is required to enable inline execution. Note that hashes do not apply to event handlers, style attributes and javascript: navigations unless the 'unsafe-hashes' keyword is present. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.

错误效果：

<img width="954" alt="image" src="https://github.com/xiaoymin/knife4j/assets/19815187/4b4399c6-faab-434e-be73-f2fb1d3497d3">
